### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement smsbombing

### ISSUE THREAD

**Issue by EdenHavertz** [ravisharma011/SMSBOMBING#1]
Tried installing from git and I got this error
ERROR: Could not find a version that satisfies the requirement smsbombing

**Comment by Soybeanxs** [comment]
I meet with this problem too,did you figured out it?

**Comment by ravisharma011** [comment]
> I meet with this problem too,did you figured out it?

Hii sorry for the trouble, I tried in my shell and its working fine. Please use Sudo apt update command before using git.
